name: notes_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  confetti: ^0.8.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.8.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  intl: ^0.20.0
  introduction_screen: ^3.1.14
  modal_progress_hud_nsn: ^0.5.1
  page_transition: ^2.1.0
  trastition_ap: ^0.0.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # Adding assets to the application
  assets:
    - assets/images/

  # Adding custom fonts to the application
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
