name: notes_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
 
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.8.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
 

dev_dependencies:
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  # Adding assets to the application
  #assets:
  # Example: Add images in the assets/images folder.
  # Adding custom fonts to the application
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
